#if !defined(AFX_ACTIVEINIFORM_H__8A7E6DD9_7769_4FA4_A8FB_76345EF6600A__INCLUDED_)
#define AFX_ACTIVEINIFORM_H__8A7E6DD9_7769_4FA4_A8FB_76345EF6600A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CActiveIniForm wrapper class

class CActiveIniForm : public CWnd
{
protected:
	DECLARE_DYNCREATE(CActiveIniForm)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd2897e2a, 0x90da, 0x4baa, { 0x90, 0x51, 0x31, 0x4, 0x8c, 0xc4, 0xef, 0xe8 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetTemplateFile();
	void SetTemplateFile(LPCTSTR);
	short GetExportFileType();
	void SetExportFileType(short);
	short GetDefaultCtrlType();
	void SetDefaultCtrlType(short);

// Operations
public:
	BOOL Save(LPCTSTR FileName, short FileType, LPCTSTR SectionName);
	BOOL Load(LPCTSTR FileName, short FileType, LPCTSTR SectionName, BOOL bCreateNewCtrl);
	BOOL LoadTemplate(LPCTSTR FileName);
	BOOL ModifyData(LPCTSTR DataName, LPCTSTR DataValue, LPCTSTR ValueString);
	CString GetData(LPCTSTR DataName);
	BOOL AddCtrl(LPCTSTR DataName, LPCTSTR CtrlType, LPCTSTR Value, LPCTSTR OtherData, LPCTSTR StaticName);
	long GetCtrlCount();
	BOOL DelCtrl(LPCTSTR DataName);
	CString GetDataShowString(LPCTSTR DataName);
	BOOL SetCtrlRecord(LPCTSTR DataName, BOOL bRecord);
	CString GetCtrl(long nIndex);
	BOOL SetCtrlPos(LPCTSTR DataName, long Index);
	long GetCtrlWnd(long dwIndex);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ACTIVEINIFORM_H__8A7E6DD9_7769_4FA4_A8FB_76345EF6600A__INCLUDED_)
