// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "activeiniform.h"

/////////////////////////////////////////////////////////////////////////////
// CActiveIniForm

IMPLEMENT_DYNCREATE(CActiveIniForm, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CActiveIniForm properties

CString CActiveIniForm::GetTemplateFile()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CActiveIniForm::SetTemplateFile(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

short CActiveIniForm::GetExportFileType()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

void CActiveIniForm::SetExportFileType(short propVal)
{
	SetProperty(0x2, VT_I2, propVal);
}

short CActiveIniForm::GetDefaultCtrlType()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

void CActiveIniForm::SetDefaultCtrlType(short propVal)
{
	SetProperty(0x3, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CActiveIniForm operations

BOOL CActiveIniForm::Save(LPCTSTR FileName, short FileType, LPCTSTR SectionName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FileName, FileType, SectionName);
	return result;
}

BOOL CActiveIniForm::Load(LPCTSTR FileName, short FileType, LPCTSTR SectionName, BOOL bCreateNewCtrl)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_BSTR VTS_BOOL;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FileName, FileType, SectionName, bCreateNewCtrl);
	return result;
}

BOOL CActiveIniForm::LoadTemplate(LPCTSTR FileName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		FileName);
	return result;
}

BOOL CActiveIniForm::ModifyData(LPCTSTR DataName, LPCTSTR DataValue, LPCTSTR ValueString)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		DataName, DataValue, ValueString);
	return result;
}

CString CActiveIniForm::GetData(LPCTSTR DataName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		DataName);
	return result;
}

BOOL CActiveIniForm::AddCtrl(LPCTSTR DataName, LPCTSTR CtrlType, LPCTSTR Value, LPCTSTR OtherData, LPCTSTR StaticName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		DataName, CtrlType, Value, OtherData, StaticName);
	return result;
}

long CActiveIniForm::GetCtrlCount()
{
	long result;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}

BOOL CActiveIniForm::DelCtrl(LPCTSTR DataName)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		DataName);
	return result;
}

CString CActiveIniForm::GetDataShowString(LPCTSTR DataName)
{
	CString result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		DataName);
	return result;
}

BOOL CActiveIniForm::SetCtrlRecord(LPCTSTR DataName, BOOL bRecord)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BOOL;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		DataName, bRecord);
	return result;
}

CString CActiveIniForm::GetCtrl(long nIndex)
{
	CString result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xe, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		nIndex);
	return result;
}

BOOL CActiveIniForm::SetCtrlPos(LPCTSTR DataName, long Index)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0xf, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		DataName, Index);
	return result;
}

long CActiveIniForm::GetCtrlWnd(long dwIndex)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0x10, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		dwIndex);
	return result;
}

void CActiveIniForm::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
