//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by WorldEditor.rc
//
#define ID_RESET                        3
#define IDD_ABOUTBOX                    100
#define IDD_WORLDEDITOR_FORM            101
#define IDD_GROUNDFILLRECT              102
#define IDD_RECT                        103
#define IDD_BOOL                        104
#define IDD_STRING                      105
#define IDD_COLOR                       106
#define IDD_INT                         107
#define IDR_MAINFRAME                   128
#define IDR_WORLDETYPE                  129
#define IDD_OBJ                         129
#define IDI_ITEM_FOLDER                 136
#define IDI_ITEM_FOLDEROPEN             137
#define IDI_ITEM_FILE                   138
#define IDI_OUTPUT_HINT                 139
#define IDI_OUTPUT_SUCCEED              140
#define IDI_OUTPUT_FORBID               141
#define IDI_OUTPUT_WARNNING             142
#define IDI_OUTPUT_NEXT                 143
#define IDI_OUTPUT_ERROR                144
#define IDI_OUTPUT_CHAT                 145
#define IDI_OUTPUT_OK                   146
#define IDI_OUTPUT_HELP                 147
#define IDI_OUTPUT_NEW                  148
#define IDI_ITEM_NPC                    151
#define IDI_ITEM_OBJECT                 152
#define IDI_ITEM_TRAP                   159
#define IDI_ITEM_LIGHT                  162
#define IDI_ITEM_CAMERA                 163
#define IDI_ITEM_ACTOR                  164
#define IDI_ITEM_TERRA                  165
#define IDI_ITEM_DOODAD                 168
#define IDI_ITEM_SETTING                171
#define IDI_ITEM_COMMAND                172
#define IDI_ITEM_ATTRIBUTE              173
#define IDI_ITEM_ATTRIBUTEFALSE         174
#define IDI_ITEM_OBSTACLE               175
#define IDI_ITEM_GROUP                  176
#define IDI_ITEM_DOODADCOMPLEX          177
#define IDI_ITEM_ROOM                   189
#define IDI_ITEM_ROAD                   190
#define IDI_ITEM_SPECIAL                191
#define IDD_SPECIAL                     192
#define IDB_BITMAP1                     194
#define IDC_DIR                         1000
#define IDC_ANIMATION                   1001
#define IDC_SPIN_ANIMATION              1002
#define IDC_DIRECTION                   1003
#define IDC_SPIN_DIRECTION              1004
#define IDC_FRAME                       1005
#define IDC_SPIN_FRAME                  1006
#define IDC_ANI_AUTOPLAY                1007
#define IDC_AUTOPLAY                    1007
#define IDC_STATIC_SPR                  1008
#define IDC_LIST                        1009
#define IDC_SPEED                       1010
#define IDC_SPIN_SPEED                  1011
#define IDC_STATIC_FRAME                1013
#define IDC_STATIC_DIRECTION            1014
#define IDC_LEFT                        1015
#define IDC_TOP                         1016
#define IDC_RIGHT                       1017
#define IDC_BOTTOM                      1018
#define IDC_TYPE                        1019
#define IDC_INT                         1020
#define IDC_BROWSE_TEMPLATE             1021
#define IDC_BROWSE_ANIMATION            1022
#define IDC_OBSTACLE_RADIUS             1023
#define IDC_VALUE1                      1024
#define IDC_ITEM1                       1025
#define IDC_DESCRIPTION1                1026
#define IDC_ITEM2                       1027
#define IDC_VALUE2                      1028
#define IDC_DESCRIPTION2                1029
#define IDC_ITEM3                       1030
#define IDC_VALUE3                      1031
#define IDC_DESCRIPTION3                1032
#define IDC_ITEM4                       1033
#define IDC_VALUE4                      1034
#define IDC_DESCRIPTION4                1035
#define IDC_ITEM5                       1036
#define IDC_VALUE5                      1037
#define IDC_DESCRIPTION5                1038
#define IDC_ITEM6                       1039
#define IDC_VALUE6                      1040
#define IDC_DESCRIPTION6                1041
#define IDC_ITEM7                       1042
#define IDC_VALUE7                      1043
#define IDC_DESCRIPTION7                1044
#define IDC_ITEM8                       1045
#define IDC_VALUE8                      1046
#define IDC_DESCRIPTION8                1047
#define IDC_ITEM9                       1048
#define IDC_VALUE9                      1049
#define IDC_DESCRIPTION9                1050
#define IDC_ITEM10                      1051
#define IDC_DYNAMIC                     1052
#define IDC_VALUE10                     1052
#define IDC_NICK                        1053
#define IDC_DESCRIPTION10               1053
#define IDC_ITEM11                      1054
#define IDC_TEMPLATE                    1055
#define IDC_VALUE11                     1055
#define IDC_DESCRIPTION11               1056
#define IDC_ITEM12                      1057
#define IDC_VALUE12                     1058
#define IDC_DESCRIPTION12               1059
#define IDC_ITEM13                      1060
#define IDC_VALUE13                     1061
#define IDC_DESCRIPTION13               1062
#define IDC_ITEM14                      1063
#define IDC_VALUE14                     1064
#define IDC_DESCRIPTION14               1065
#define IDC_ITEM15                      1066
#define IDC_VALUE15                     1067
#define IDC_DESCRIPTION15               1068
#define IDC_ITEM16                      1069
#define IDC_VALUE16                     1070
#define IDC_DESCRIPTION16               1071
#define IDC_OBSTACLE_KIND               2020
#define IDC_OBSTACLE_TYPE               2021
#define IDC_BOOL                        20000
#define IDC_STRING                      20001
#define IDC_ACTIVEINIFORMCTRL1          20002
#define IDD_NPCSETTING                  20002
#define IDD_SELECT                      20003
#define IDC_RADIO2                      20004
#define IDD_OBSTACLE                    20004
#define IDC_RADIO3                      20005
#define IDC_COMBO_SORT                  20006
#define IDC_COMBO_KIND                  20007
#define IDC_COMBO_FILTER                20008
#define IDC_COMBO_FILTERPARAM           20009
#define ID_TOOL_RESOURCEEDIT            32771
#define ID_TOOLS_RESOURCEEDITOR         32773
#define ID_EDIT_UNDOTOBEGIN             32775
#define ID_EDIT_REDOTOEND               32776
#define ID_GROUND_FILLRECT              32778
#define ID_TOOLS_MAPCONVERT             32779
#define ID_TOOLS_IMAGECREATE            32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        195
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
