//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ResourceManager.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RESOURCEMANAGER_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDI_ITEM_FOLDER                 136
#define IDI_ITEM_FOLDEROPEN             137
#define IDI_ITEM_FILE                   138
#define IDI_ITEM_DOODADCOMPLEX          148
#define IDI_ITEM_NPC                    151
#define IDI_ITEM_OBJECT                 152
#define IDI_ITEM_TRAP                   159
#define IDI_ITEM_LIGHT                  162
#define IDI_ITEM_CAMERA                 163
#define IDI_ITEM_ACTOR                  164
#define IDI_ITEM_TERRA                  165
#define IDI_ITEM_DOODAD                 168
#define IDI_ITEM_FOLDERHAVEFILE         169
#define IDD_PROPERTY                    169
#define IDI_ITEM_FOLDERHAVEFILEOPEN     170
#define IDI_ITEM_SETTING                171
#define IDI_ITEM_COMMAND                172
#define IDD_DIVIDE                      172
#define IDI_ITEM_ATTRIBUTE              173
#define IDI_ITEM_ATTRIBUTEFALSE         174
#define IDI_ITEM_OBSTACLE               175
#define IDI_ITEM_GROUP                  176
#define IDI_ITEM_ROOM                   189
#define IDI_ITEM_ROAD                   190
#define IDI_ITEM_SPECIAL                191
#define IDC_TREE_SOURCE                 1000
#define IDC_TREE_DES                    1001
#define IDC_CONVERT                     1002
#define IDC_PATH_SRC                    1003
#define IDC_ANIMATION                   1003
#define IDC_DIR_SRC                     1004
#define IDC_SPIN_ANIMATION              1004
#define IDC_PATH_DES                    1005
#define IDC_DIRECTION                   1005
#define IDC_DIR_DES                     1006
#define IDC_SPIN_DIRECTION              1006
#define IDC_AUTOPLAY                    1007
#define IDC_FRAME                       1008
#define IDC_SPIN_FRAME                  1009
#define IDC_STATIC_SPR                  1010
#define IDC_SPEED                       1011
#define IDC_COMBO_ICON                  1011
#define IDC_SPIN_SPEED                  1012
#define IDC_EDIT_FILE                   1012
#define IDC_STATIC_FRAME                1013
#define IDC_STATIC_DIRECTION            1014
#define IDC_COMBO_TYPE                  1014
#define IDC_PLANETYPE                   1015
#define IDC_X                           1016
#define IDC_Y                           1017
#define IDC_SAVE                        1018
#define IDC_SHOWCENTER                  1019
#define IDC_LIGHTING                    1020
#define IDC_LIGHTED                     1021
#define IDC_LAYER                       1022
#define IDC_OBSTACLETYPE                1023
#define IDC_CENTERX                     1024
#define IDC_CENTERY                     1025
#define IDC_SAVETYPE                    1026
#define IDC_ANGLEXY                     1027
#define IDC_TEXTUREUSE                  1028
#define IDC_RADIUS                      1029
#define IDC_DOODADTYPE                  1030
#define IDC_ANGLEZ                      1030
#define IDC_GEOMETRY                    1031
#define IDC_LEFTEXTRA                   1031
#define IDC_KIND                        1031
#define IDC_RIGHTEXTRA                  1032
#define IDC_OBSTACLE                    1032
#define IDC_VERSORT                     1032
#define IDC_ANISPEED                    1033
#define IDC_LISTPOINT                   1034
#define IDC_LOCATE                      1034
#define IDC_ANILOOP                     1035
#define IDC_SPINX                       1037
#define IDC_DELETEPOINT                 1039
#define IDC_HEIGHT                      1040
#define IDC_ADDPOINT                    1042
#define IDC_SPINY                       1044
#define IDC_ALL                         1047
#define IDC_STATIC_WIDTH                1048
#define IDC_ALL_PLANETYPE               1048
#define IDC_STATIC_HEIGHT               1049
#define IDC_ALL_LIGHTING                1049
#define IDC_UP                          1050
#define IDC_ALL_LIGHTED                 1050
#define IDC_RIGHT                       1051
#define IDC_ALPHA                       1051
#define IDC_GETCENTER                   1051
#define IDC_LEFT                        1052
#define IDC_ALL_RADIUS                  1052
#define IDC_DOWN                        1053
#define IDC_ALL_LAYER                   1053
#define ID_DIVIDED                      1054
#define IDC_ALL_VERSORT                 1054
#define IDC_ALL_ANGLEXY                 1055
#define IDC_SPIN_HEIGHT                 1056
#define IDC_ALL_ANGLEZ                  1056
#define IDC_SPIN_HEIGHT2                1057
#define IDC_ALL_HEIGHT                  1057
#define IDC_SPIN_HEIGHT3                1058
#define IDC_SPR2TXT                     1058
#define IDC_ALL_OBSTACLETYPE            1059
#define IDC_WIDE                        1060
#define IDC_ALL_CENTERX                 1060
#define IDC_HIGH                        1061
#define IDC_ALPHAFORMAT                 1061
#define IDC_ALPHASET                    1062
#define IDC_ALL_CENTERY                 1063
#define IDC_ALL_SAVETYPE                1064
#define IDC_ALL_TEXTUREUSE              1065
#define IDC_DISPLAYALPHA                1066
#define IDC_ALL_KIND                    1066
#define IDC_CENTERSETTING               1067
#define IDC_ALL_ANISPEED                1068
#define IDC_LOG                         1069
#define IDC_SHADOW                      1070
#define IDC_LOG2                        1071
#define IDC_ADDSPRINFO                  1071
#define IDC_INI2TXT                     1072
#define IDC_ALL_ANILOOP                 1073

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
